### ISSUE TITLE
Shouldn't a CHECKPOINT be performed before the DBCC DROPCLEANBUFFERS

### ISSUE THREAD

**Issue by buckleyGI** [ErikEJ/SqlQueryStress#145]
Hi,

Was there a reason not to do the CHECKPOINT? If not I can contribute with a PR

https://blog.sqlauthority.com/2019/06/17/sql-server-impact-of-checkpoint-and-dbcc-dropcleanbuffers-on-memory/

Kind Regards, Tom

**Comment by ErikEJ** [comment]
A PR would be great

**Comment by ErikEJ** [comment]
Any updates on this?

**Comment by buckleyGI** [comment]
AFAIK The CHECKPOINT statement is advised when doing comparative performance tests.
If anyone can confirm and find this useful I'll implement this.

**Comment by ErikEJ** [comment]
@BrentOzar Thoughts?

**Comment by BrentOzar** [comment]
**Short answer:** yes, the person who would click the Clean Buffers button would want to do the CHECKPOINT first. However, I don't like either the Clean Buffers or Free Cache buttons, I've never clicked them, and I don't think anyone else should, either.

**Long answer:** performance tests should vaguely mimic what you're expecting to happen in real life. In real life, you don't start with empty memory - your servers have existing cache because they've been warmed up over the previous days. It's not like you restart the SQL Server each morning to prepare for the day's loads (and if you do, you should stop doing that.)

If your data mostly fits in memory, then when the real workload happens, it's going to be in memory already. There's no point in clearing the buffer pool - you're just testing storage at that point, which is irrelevant if your data mostly fits in memory.

If your data does NOT mostly fit in memory, then in the real-world workloads, you can't predict what's going to be in cache at the moment your workload runs - but it doesn't matter, because your queries are likely asking for data that is NOT in memory. Therefore, clearing the buffer pool doesn't really make a difference there either.

However, I'm not trying to get those buttons taken away. If people want to stress test their storage, okay, great - in that case, you would also want to run a checkpoint prior to dropping clean buffers. But if you wanna stress test storage, there are much more appropriate (and accurate) tools out there.

**Comment by BrentOzar** [comment]
I should also add - @buckleyGI, don't feel bad for suggesting it! I've repeatedly heard that bad advice from lots of sources, even to the point of "restart your SQL Server between each load test".

**Comment by buckleyGI** [comment]
Thanks for weighing in Brent. I used your blog post about this tool to get up to speed so appreciate it.

> yes, the person who would click the Clean Buffers button would want to do the CHECKPOINT first

Then for consistency I think it makes sense to accommodate this viewpoint and add the CHECKPOINT. I'll create a PR.

**Comment by ErikEJ** [comment]
@buckleyGI Any plans to create a PR?
